# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD WorkFlow

on:
  push:
    branches: [ "develop" ]

jobs:

  run-affected-unit-tests:
    name: Run unit tests
    defaults:
        run:
         working-directory: './ConcertCasus'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

     
    - run: npm ci
    - run: npm run  build --if-present --output-path=./ConcertCasus/dist/ConcertCasus
    - run: npm test
    
  deploy:
    runs-on: ubuntu-latest
    needs: run-affected-unit-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Build site
        run: npm run build --if-present --output-path=./ConcertCasus/dist/ConcertCasus
        
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: M1hBJmw1kE9SYcxbr42ZvjTjxwks-_Kdbjn6ZsW0SD0
          NETLIFY_SITE_ID: c185e400-86f4-4be8-95e7-78471f31f216
        run: netlify deploy --prod --dir=/ConcertCasus_Angular/ConcertCasus/dist

          



    
   
    
