npm cache verify# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD WorkFlow

on:
  push:
    branches: [ "develop" ]

jobs:

 run-affected-unit-tests:
        name: Run unit tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  node-version: '16.x'
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - run: npm ci
            - run: npm test
    
